/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import demo.data.LinkedListNode;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LinkedListNodeTest {

}
