/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Stack;

public class Library {
    // declaring the array - no memory has been allocated
    int[] ages;

    // we know the array items
    double[] prices = new double[]{ 12.3, 45.7 };

    String[] planets = new String[]{ "Pluto", "Mars", "Earth", "Jupiter" };

    // we know the size of the array but not the values
    String[] names = new String[25];

    public Library() {
        System.out.println("application started");
    }

    public void list() {
        // polymorphism
        // programming to the interface
        List<String> programmingLanguages = new ArrayList<>();
        programmingLanguages = new Stack<>();

        // not polymorphism
        ArrayList<String> ides = new ArrayList<>();
//        ides = new HashMap<>();

        programmingLanguages.add("JSON");
        programmingLanguages.add("XML");
        programmingLanguages.add("JAVA");
        programmingLanguages.add("C");
        programmingLanguages.add("C++");
        programmingLanguages.add("PYTHON");

        programmingLanguages.add(2, "FORTRAN");

        System.out.println("the language is => " + programmingLanguages.get(5));

    }

    public boolean someLibraryMethod() {

        // prints and accesses data in the array using the array index
        // array indexes ALWAYS starts at index 0
        System.out.println("the price is => " + prices[0]);

        return true;
    }

    /**
     * trhis is a looping method
     * @param num5 nuimber 1
     * @param name instructor name
     * @return the val;ue 2
     */
    public int looping(int num5, String name) {
        // traditional loop
        int counter = 0;
        while(counter < planets.length) {
            System.out.println("hi my name is slim shady i am from => " + planets[counter]);
            counter++;
        }

        int whileCounter = 0;
        int num1 = 10;
        double num2 = 34.8;
        double sum = 0;
        do {
            sum = sum + (num1 + num2);
            System.out.println("the value is => " + sum + " the count is => " + whileCounter);
            whileCounter++;
        } while (whileCounter <= 5);

        // traditional for loop
        for (int index = 0; index < planets.length; index++) {
            System.out.println("hi my name is marshall matthers i am from => " + planets[index]);
        }

        // enhanced for loop
        for (String planet : planets) {
            System.out.println("the planet is => " + planet);
        }

        return 2;
    }

    public void scrapper(String url) {
        Document doc = null;

        try {
            doc = Jsoup.connect(url).get();
        } catch (IOException exception) {
            System.out.println("some thing went wrong => " + exception.getMessage());
        }

        assert doc != null;
        System.out.println(doc.title());
        Elements newsHeadlines = doc.select("#mp-itn b a");
        for (Element headline : newsHeadlines) {
            System.out.printf("%s\n\t%s", headline.attr("title"), headline.absUrl("href"));
        }
    }
}
