/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linklist.data;

import data.Node;

public class LinkedListNode extends Node {
    public LinkedListNode(String data) {
        super(data);
    }
}
